#!/bin/tcsh

#PBS -m abe
#PBS -N dynspec_reprocessing
#PBS -l nodes=1:ppn=48
#PBS -l walltime=18:00:00
#PBS -o /beegfs/car/mjh/torque
#PBS -e /beegfs/car/mjh/torque
#PBS -q core96
#PBS -W group_list=lofar

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

echo Obsid is $OBSID

cd /beegfs/lofar/deepfields/ELAIS-N1_DR2_radio/full
bash -c /home/mjh/pipeline-master/lotss-hba-survey/torque/dynspec-EN1.sh
