#!/bin/tcsh

#PBS -N mosaic
#PBS -l nodes=1:ppn=32
#PBS -l walltime=20:00:00
#PBS -q main
#PBS -o /beegfs/car/mjh/torque
#PBS -e /beegfs/car/mjh/torque

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

echo Field is $FIELD

bash -c /home/mjh/pipeline-offsetpointings/lotss-hba-survey/torque/mosaic_dr3.sh
