#!/bin/tcsh

#PBS -m abe
#PBS -N lbcal
#PBS -l nodes=smp4:ppn=32
#PBS -l walltime=4:00:00
#PBS -k oe
#PBS -q smp

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo ------------------------------------------------------

echo Obsid is $OBSID

/soft/singularity-3.8.4/bin/singularity exec -B/home,/beegfs,/scratch /beegfs/car/mjh/flocs/lofar_sksp_v4.4.0_cascadelake_cascadelake_ddf_mkl_cuda.sif /home/mjh/pipeline-lbcal/lotss-hba-survey/torque/lbcal_cwltool_smp4.sh $OBSID



